language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-fulltest-app
  api_key:
    secure: rlsAuFgBbVWPQa3Tgp1zl1ZU2dfLUnwiIHsfDmWu2Ypx2gFTRCNR6OEBCXR6PEBPX6s45Na972pQVU0wwVstwJsMzQcYE5ZlJdZoXJ1Of5DjCLb/cP5PxX3UGrA+d89srRsxyenCREZxnPb6FhE4S/CDR89TQlZDySzUMLESkRWjVe6ZDP5M7KMfRkIAMZE2T2pDXHcvBRC2CDybSopBuXtaF/f0c17XbKFsoZWbezRpwHEJkuJQvgz+glMG+fIQvlm5rqQqPZ0GRTGtlgcgxrPzyit1Pgf5KP6HrrOWWmXy46XUgQflhhyyZT536KaPdv6Pa2W/6wdcAH0kd4AymhmD+TKok17OyLsd1P+/mpqPCxRCUqHqWrCOIIc+OeN8SBUDO9gQN4Z/kloKsaxpYDJtrVqXnn4SC4+Xr3Bv1MFk1n4EsWIE13zCmxEVLy/pQiHRd5FeSMvvfPd7irYd3Z2MIA2fFcr+k9xwcKeyZq11fXKhwktHCf8+DLSPsSNeT8WP3wMUI0Xal3IiTwM5lEM+Bcxe79GkigH78dK2RdkLjpkyqV3lzdv80mWJnYowoKYb/LZ+0bRUqRfIt4HplQml3ilg8x6w8mVxvYqS4OI3BWBTlKAyg1h1vuk6OVCz73q841Xy8Y3M12wXFaGwR/pjVZvH6O2LBmQ3C3LafmM=
  on:
    repo: degreeproject/angular-fulltest-app
    branch: master
