language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-fulltest-app
  api_key:
    secure: YkMp3316/GyBZxUIcRTeK12NV6qWijwwMqPGjnMX7WlAFe5X47hCTD+nQxbZdmGSRkR6T70wIABjvF8j9n5f+nUWdqVr9vtxe/xHYAW1N/HV+tTEbzJLaS+iXCYxwsXjp3nDzZPdA1vloo1nkoEVxVCydTSce6QFCEMyqZrGRHHU7i1B4X5IbOJ14S7LPvf/EsRToOZeEB/gfYNUUYPYEj76zxu6bWdUrRKhMza/vjGbuCLSy1Fu4dyTYVEoKrbPV3LKh2H2N6oLOMpyK7EamXzFV2yw+o4CO4RNijnX3DGTJqeVrLVMH8HvdoDF2c0Fv34gAixV//Vn5DO/Zr8c1qwnpd1CZDFEekAENWoWu9HR2g38CPLeDD9eF218e3zMam93Nh09dbR9FgP+Q91ZBUXX1QJyZ9Oi9yY16PQFpt7hPp88+4yAfuzZNJ1/EGXd/+ssZKSvxcmBK/p+dRSTDsH4vpxrg/dxqopnP23MTvBnC1ncInEDXpprPv9uWNe0TmITBXjXM+eOnlcO07XUqn9KlDMhhda64/z61CZ30QcXoIYI/cqlyDRgPaIdCdLFSQMFxtcPhVVlcqlBM4usHmsuN0Mrncbd7i4ix6fQfaRfO6wb5Lz/Ayr131NPhlPdJOrL4/yIOk9m7us124MsJXdvQyUtj1rlQZK+LsgK0+8=
  on:
    repo: degreeproject/angular-fulltest-app
    branch: master
