language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-test-app
  api_key:
    secure: OYayEaTQ/pFj0a7xPq+NfEcyYSybEdRzjqtNJ2MoY99z9YKzUX5o25Mc6rkU+OOMstwiFmqDVGwBZiM5IoqNA4CFYljbbtzDLXSYN3ueFmgRii2XbGWaLzQbfFqykPTRCZvqF0DjeAee8tKAyjP3ouDTEnlu+LWUpC54ZBNpuFoN10NpavwT9V8LX+t2JQfv1rdeBQYqPwkDfqQoV8Mh3sHd0skZ+ITgVl44OneH3wHsiYvGm5PCUfFM2yD8bsCxFQmPIKcTGAMZB22ZFGcrc096TiMC+sWIngG2XSzxc3ZQBvKbUURQlhsrUD/BtF/aSowUYwhCJhQmVRxmjZG1L76VX2vbetcBJC6BoYU489kQcHW/DAr8gt+FspJ1SrKxMfFTrcMhoNDDJbWZhEHRDhqdkupB2m/X46YVZVuDVnp/i7All4PPI5tdN3sHev2MYzJqMzFKc4UX/n2lOAA7IhDEZQQcGBaHZMBgiC5y2VQT89/2CbN/NkwRhYw2IRDi6EfFK/sr9ehDVw+1QtTedjyN6QXrbT8b6IjUmQRHM+nsHcUrUsoDmNRNMJzUT7lPzGbV9mI4V4rhfIW5kaywIJ3BEPzB1Y/U4dsIoYGQbVUjZ3b3+nslrXPN8ryCOeapc33bJt6DdLF5LV+qDJFM+D6kvtmtQJ3dZuZVAa6zJK4=
  on:
    repo: degreeproject/angular-fulltest-app
    branch: master
