language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-test-app
  api_key:
    secure: Cl6N9t8Kntvl7ZcFZiiBwQF/HmU5qxdGtJJtEVdE7GlrBgDGiNXlwcxjQIcfSoZmR6rNyAvrVN7xq/FAJtwYRD/wqyDkl7G0NZ9AqGYhkDTX9inIkJNuj296J03yU0ulGAJTheAUBPyZcT3sLKdGO/irdgEog8kUVG0rssku2c2W1kwbGlXi/r12EtLtCkmqMvNIHp9xo7O7KAB0NoilxVAjoruX6VNvcfSRbYZOvD1v7+k9ET/fGNMMJ9hzNWZrc/owI1t8hEpvelqXTWVlbS1gUI34kTk75Lx7tSGN93kwUE8Qkmpt0wwRbd90N466M+3pAvPw0I8lWdpEdRGBfCL5ZQGgmvU/ar+rZ677NnVH1RoxS94aHY7wIt2jgz0C4teT44xG92S5Hd64+3p96SVg4x87LtOm9knklAwNQyqZxh/KmFiw6BOqv/XDAtYMNcJPDXPQCwuDHuhpEboGCygHJ1Khf5Ygkbxs9psKaDXfkxSVuzx3LRigS3ZYctWkS/BWedos4ePtKJhoUMrTAcI+W1catdq8J8xXSLzYbPL9CWnOMMl0dsJEBA0aLJ9UMqHn+ID93wBOuKSwelxFM3xROpMsz+imBpbXDfUpa14uSn0tm/IRJgt3uGs6inHVgj/zKv06iDfiI89EOrlwioyufw+F4xcAuXX4OJAicLQ=
  on:
    repo: degreeproject/angular-fulltest-app
    branch: master
